---
- name: create console-setup
  file:
    path: /etc/default/console-setup
    owner: root
    group: root
    state: touch

- name: set font in console-setup
  lineinfile:
    path: /etc/default/console-setup
    line: 'FONT=Lat15-Terminus12x6.psf.gz'
    state: present

- name: set colors in terminal for sessions
  lineinfile:
    path: /etc/profile
    line: 'force_color_prompt=yes'
    state: present

- name: set colors in terminal for sessions
  lineinfile:
    path: /etc/profile
    line: 'force_color_prompt=no'
    state: absent
