---
- name: install packages
  apt:
    pkg:
    - unzip
    - iptables
    - iptables-persistent
    - python-setuptools
    - libavahi-compat-libdnssd1
    - libnss-mdns
    - byobu
    - htop
    - cpufrequtils
    state: present
    autoremove: yes
    autoclean: yes
    upgrade: dist
    update_cache: yes

- name: enable ssh
  service:
    name: ssh
    enabled: yes

- name: enable root login via ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PermitRootLogin yes'
    state: present

- name: get date
  command: 'date --iso-8601'
  register: build_date

- name: Register ReFactor version
  script:
    cmd: '{{ role_path }}/files/get_refactor_version.sh'
  register: version

- name: write dogtag
  copy:
    dest: '/etc/{{ dogtag }}'
    content: '{{ version.stdout }} {{ build_date.stdout }}'

- name: set hostname
  copy:
    dest: /etc/hostname
    content: "{{ platform }}\n"

- name: set root password
  shell:
    cmd: "echo 'root:kamikaze' | chpasswd"

- name: write issue and issue.net
  copy:
    dest: '{{ item }}'
    content: |
      {{ version.stdout }}

      Check that nothing is printing before any intensive operation!
  with_items:
    - /etc/issue.net
    - /etc/issue

- name: Recore - copy dtb and dts device trees
  copy:
    src: '{{ role_path }}/files/{{ item }}'
    dest: "/boot/dtb/allwinner/{{ item }}"
  with_items:
    - sun50i-a64-recore-a2.dtb
    - sun50i-a64-recore-a2.dts
    - sun50i-a64-recore-a3.dtb
    - sun50i-a64-recore-a3.dts
    - sun50i-a64-recore-a4.dtb
    - sun50i-a64-recore-a4.dts

- name: Recore - rename dtb device tree file
  copy:
    src: /boot/dtb/allwinner/sun50i-a64-recore-a4.dtb
    dest: /boot/dtb/allwinner/sun50i-a64-recore.dtb

- name: Recore - Replace platform name
  replace:
    path: /etc/armbian-release
    regexp: "{{ item.regexp1 }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp1: 'Pine64', replace: 'Recore'}
    - { regexp1: 'pine64', replace: 'recore'}

- name: Recore - Service - Ensure ethernet comes up
  copy:
    src: '{{ role_path }}/files/recore-a4-eth-fix.service'
    dest: /etc/systemd/system/

- name: Recore - Script - Ensure ethernet comes up
  copy:
    src: '{{ role_path }}/files/recore-a4-eth-fix'
    dest: /usr/lib/
    mode: +x

- name: Recore - Enable eth fix
  shell: systemctl enable recore-a4-eth-fix

- name: Recore - Fix haveged
  replace:
    path: /etc/default/haveged
    regexp: '"-w 1024"'
    replace: '"-w 1024 -d 16"'
