---
- name: update package list
  apt:
    update_cache: yes

- name: upgrade packages
  apt:
    upgrade: dist

- name: install packages
  apt:
    pkg:
    - unzip
    - iptables
    - iptables-persistent
    - python-pip
    - python3-pip
    - python-dev
    - libavahi-compat-libdnssd1
    - libnss-mdns
    - byobu
    - htop
    - cpufrequtils
    - pkg-config
    - python3-dev
    - pkg-config
    - firmware-realtek
    state: present
    autoremove: yes
    autoclean: yes

- name: enable ssh
  service:
    name: ssh
    enabled: yes

- name: enable root login via ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PermitRootLogin yes'
    state: present

- name: get date
  command: 'date --iso-8601'
  register: build_date

- name: Register ReFactor version
  script:
    cmd: '{{ role_path }}/files/get_refactor_version.sh'
  register: version

- name: write dogtag
  copy:
    dest: '/etc/{{ dogtag }}'
    content: '{{ version.stdout }} {{ build_date.stdout }}'

- name: set hostname
  copy:
    dest: /etc/hostname
    content: '{{ platform }}\n'

- name: set root password
  shell:
    cmd: "echo 'root:kamikaze' | chpasswd"

- name: write issue and issue.net
  copy:
    dest: '{{ item }}'
    content: |
      {{ version.stdout }}

      Check that nothing is printing before any intensive operation!
  with_items:
    - /etc/issue.net
    - /etc/issue

- name: Recore - fetch dtb and dts device trees
  get_url:
    url: "https://github.com/intelligent-agent/Recore/raw/master/Device_tree/{{ item }}"
    dest: "/boot/dtb/allwinner/{{ item }}"
  with_items:
    - sun50i-a64-recore-a2.dtb
    - sun50i-a64-recore-a2.dts
    - sun50i-a64-recore-a3.dtb
    - sun50i-a64-recore-a3.dts
    - sun50i-a64-recore-a4.dtb
    - sun50i-a64-recore-a4.dts

- name: Recore - Replace platform name
  replace:
    path: /etc/armbian-release
    regexp: "{{ item.regexp1 }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp1: 'Pine64', replace: 'Recore'}
    - { regexp1: 'pine64', replace: 'recore'}
