---
- name: Replicape - Install Klipper
  include: replicape.yml
  when: platform == 'replicape'

- name: Recore - Install Klipper
  include: recore.yml
  when: platform == 'recore'

- name: Pi - Install Klipper
  include: pi.yml
  when: platform == 'pi'

- name: Pi64 - Install Klipper
  include: pi.yml
  when: platform == 'pi64'
