appearance:
  name: KAMIKAZE
feature: {}
folder:
  uploads: /usr/share/models
gcodeViewer: {}
plugins:
  softwareupdate:
    _config_version: 4
    checks:
      Redeem:
        checkout_folder: /usr/local/src/redeem
        type: git_commit
        update_script: '{python} "/usr/local/src/redeem/update-redeem.py" --python="{python}" --sudo "{folder}" "{target}"'
        restart: 'echo "Redeem dummy restart"'
      octoprint:
        checkout_folder: /home/debian/OctoPrint
        prerelease: false
        type: github_release
      Kamikaze:
        checkout_folder: /usr/src/Umikaze
        type: git_commit
        update_script: '/usr/src/Umikaze/update-kamikaze.sh'
        restart: 'echo "Kamikaze dummy restart"'
printerParameters: {}
server:
  firstRun: true
  commands:
    serverRestartCommand: sudo systemctl restart octoprint.service
    systemRestartCommand: sudo reboot
    systemShutdownCommand: sudo shutdown -h now
terminalFilters:
  - name: Suppress temperature messages
    regex: '(Send: (N\d+\s+)?M105)|(Recv:\s+(ok\s+)?.*\s(T\d*):\d+)'
  - name: Suppress SD status messages
    regex: '(Send: (N\d+\s+)?M27)|(Recv: SD printing byte)|(Recv: Not SD printing)'
  - name: Suppress wait responses
    regex: 'Recv: (wait)|(ok)$'
temperature: {}
webcam:
  stream: http://arm.local:8080/?action=stream
  snapshot: http://localhost:8080/?action=snapshot
  ffmpeg: /usr/bin/avconv
controls:
  - name: Stepper current and microstepping
    layout: vertical
    children:
    - name: Set
      layout: vertical
      commands:
       - M906 X%(current_x)s
       - M909 X%(microstepping_x)s
      input:
      - default: 500
        name: Current X
        parameter: current_x
        slider:
          max: 2500
          min: 1
          step: 1
      - default: 4
        name: Microstepping X
        parameter: microstepping_x
        slider:
          max: 7
          min: 0
          step: 1
    - name: Set
      layout: vertical
      commands:
       - M906 Y%(current_y)s
       - M909 Y%(microstepping_y)s
      input:
      - default: 500
        name: Current Y
        parameter: current_y
        slider:
          max: 2500
          min: 1
          step: 1
      - default: 4
        name: Microstepping Y
        parameter: microstepping_y
        slider:
          max: 7
          min: 0
          step: 1
    - name: Set
      layout: vertical
      commands:
       - M906 Z%(current_z)s
       - M909 Z%(microstepping_z)s
      input:
      - default: 500
        name: Current Z
        parameter: current_z
        slider:
          max: 2500
          min: 1
          step: 1
      - default: 4
        name: Microstepping Z
        parameter: microstepping_z
        slider:
          max: 7
          min: 0
          step: 1
    - name: Set
      layout: vertical
      commands:
       - M906 E%(current_e)s
       - M909 E%(microstepping_e)s
      input:
      - default: 500
        name: Current E
        parameter: current_e
        slider:
          max: 2500
          min: 1
          step: 1
      - default: 4
        name: Microstepping E
        parameter: microstepping_e
        slider:
          max: 7
          min: 0
          step: 1
    - name: Set
      layout: vertical
      commands:
       - M906 H%(current_h)s
       - M909 H%(microstepping_h)s
      input:
      - default: 500
        name: Current H
        parameter: current_h
        slider:
          max: 2500
          min: 1
          step: 1
      - default: 4
        name: Microstepping H
        parameter: microstepping_h
        slider:
          max: 7
          min: 0
          step: 1
  - name: Stepper steps pr mm and direction
    layout: vertical
    children:
    - name: Set
      layout: vertical
      commands:
       - M569 X%(direction_x)s
       - M92  X%(steps_pr_mm_x)s
      input:
      - default: 10
        name: Steps pr mm X
        parameter: steps_pr_mm_x
      - default: 1
        name: Invert X
        parameter: direction_x
        slider:
          max: 1
          min: -1
          step: 2
    - name: Set
      layout: vertical
      commands:
       - M569 Y%(direction_y)s
       - M92  Y%(steps_pr_mm_y)s
      input:
      - default: 10
        name: Steps pr mm Y
        parameter: steps_pr_mm_y
      - default: 1
        name: Invert Y
        parameter: direction_y
        slider:
          max: 1
          min: -1
          step: 2
    - name: Set
      layout: vertical
      commands:
       - M569 Z%(direction_z)s
       - M92  Z%(steps_pr_mm_z)s
      input:
      - default: 10
        name: Steps pr mm Z
        parameter: steps_pr_mm_z
      - default: 1
        name: Invert Z
        parameter: direction_z
        slider:
          max: 1
          min: -1
          step: 2
    - name: Set
      layout: vertical
      commands:
       - M569 E%(direction_e)s
       - M92  E%(steps_pr_mm_e)s
      input:
      - default: 10
        name: Steps pr mm E
        parameter: steps_pr_mm_e
      - default: 1
        name: Invert E
        parameter: direction_e
        slider:
          max: 1
          min: -1
          step: 2
    - name: Set
      layout: vertical
      commands:
       - M569 H%(direction_h)s
       - M92  H%(steps_pr_mm_h)s
      input:
      - default: 10
        name: Steps pr mm H
        parameter: steps_pr_mm_h
      - default: 1
        name: Invert H
        parameter: direction_h
        slider:
          max: 1
          min: -1
          step: 2
