---
- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://feeds.iagent.no/debian buster main
    state: present

- name: add iagent feeds
  ansible.builtin.apt_key:
    url: http://feeds.iagent.no/debian/iagent.public.key
    state: present

- name: update package list
  apt:
    update_cache: yes

- name: install dependencies
  apt:
    pkg:
      - python3-setuptools
      - python3-gi
      - python3-pip
      - python3-dev
      - libdbus-1-dev
      - libglib2.0-dev
      - python3-cairo
      - python3-gi-cairo
      - python3-networkmanager
      - python3-tornado
      - python3-requests
      - gir1.2-mx
      - gir1.2-mash-0.3-0
    state: present
    force: yes

- name: clone toggle from git
  git:
    repo: https://github.com/intelligent-agent/toggle
    dest: '{{ toggle_home }}/src/toggle'
    version: dev
    depth: 1

- name: copy toggle service file
  copy:
    src: '{{ role_path }}/files/toggle_recore.service'
    dest: /lib/systemd/system/toggle.service

- name: grant sudo to octo user for restarting toggle service
  lineinfile:
    path: /etc/sudoers.d/octo
    line: '%octo ALL=NOPASSWD: /bin/systemctl restart toggle.service'
    state: present

- name: install toggle in venv
  shell:
    cmd: 'cd {{ toggle_home }}/src/toggle ; {{ toggle_home }}/bin/pip install -e . -r requirements.txt ; {{ toggle_home }}/bin/python setup.py clean install'

- name: touch the local.cfg file
  file:
    path: /etc/toggle/local.cfg
    state: touch
    owner: octo
    group: octo

- name: enable the toggle service
  service:
    name: toggle
    enabled: yes

- name: clone octoprint toggle plugin from git
  git:
    repo: https://github.com/intelligent-agent/octoprint_toggle
    dest: /usr/src/octoprint_toggle

- name: install octoprint toggle plugin in virtualenv
  shell:
    cmd: 'cd /usr/src/octoprint_toggle; {{ octoprint_home }}/venv/bin/python setup.py clean install'

- name: install sudoers entry for toggle restart
  lineinfile:
    path: /etc/sudoers.d/octo
    line: '%octo ALL=NOPASSWD: /usr/bin/make -C /usr/src/toggle install'
    state: present

- name: enable toggle service
  service:
    name: toggle
    enabled: yes
