---
- name: clone octoprint klipper plugin
  git:
    repo: https://github.com/AliceGrey/OctoprintKlipperPlugin.git
    version: configSanityCheck
    dest: /usr/src/octoprint_klipper

- name: install octoprint klipper plugin in Octoprint virtual env
  shell:
    cmd: 'cd /usr/src/octoprint_klipper ; {{ octoprint_home }}/venv/bin/python setup.py clean install'
